# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: PublishCodeCoverageResults@1
  displayName: "Publish Code Coverage results"
  inputs:
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/target/site/jacoco/jacoco.xml'
    pathToSources: '$(System.DefaultWorkingDirectory)/**/src/main/java/'
    additionalCodeCoverageFiles: '$(System.DefaultWorkingDirectory)/**/*.exec'
- task: PublishTestResults@2
  displayName: "Publish test results"
  inputs:
    testResultsFormat: "JUnit"
    mergeTestResults: true # Optional
# - task: SonarCloudPrepare@1
#   inputs:
#     SonarCloud: 'SonarCloud'
#     organization: 'san-sample-projects'
#     scannerMode: 'Other'
#     projectKey: 'bank-api-spring-boot'
    
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'san-sample-projects'
    scannerMode: 'Other'
    projectKey: 'san-sample-projects_bank-api-spring-boot'

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'